from pathlib import Path

ROOT_DIR = Path(__file__).parent
ASSETS_DIR = ROOT_DIR / 'assets'
WINDOW_ICON_PATH = ASSETS_DIR / 'icon.png'

# Tamanhos
BIG_FONT_SIZE = 40
MEDIUM_FONT_SIZE = 24
SMALL_FONT_SIZE = 18
DISPLAY_TEXT_MARGIN = 15
MINIMUM_WIDTH = 500

# Cores
PRIMARY_COLOR='#1e81b0'
DARK_PRIMARY_COLOR='#16658a'
DARKEST_PRIMARY_COLOR ='#115270'